//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dokumanlar()
        {
            this.Kayitlar = new HashSet<Kayitlar>();
        }
    
        public int dokuman_id { get; set; }
        public string dokuman_ad { get; set; }
        public string dokuman_yazar { get; set; }
        public string dokuman_yayinci { get; set; }
        public Nullable<int> dokuman_sayfaSayisi { get; set; }
        public Nullable<System.DateTime> dokuman_basimTarihi { get; set; }
        public string dokuman_turu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayitlar> Kayitlar { get; set; }
    }
}
