//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dokumanlar
    {
        public int dokuman_id { get; set; }
        public string dokuman_ad { get; set; }
        public string dokuman_yazar { get; set; }
        public string dokuman_yayinci { get; set; }
        public Nullable<int> dokuman_sayfaSayisi { get; set; }
        public Nullable<System.DateTime> dokuman_basimTarihi { get; set; }
    }
}
